"""empty message

Revision ID: 751e5336d902
Revises: 7871bae9a911
Create Date: 2026-04-08 20:29:52.082755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751e5336d902'
down_revision: Union[str, Sequence[str], None] = '7871bae9a911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_demo_id', 'demo', ['id'])
    op.drop_column('demo', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo', sa.Column('avatar', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.drop_constraint('uq_demo_id', 'demo', type_='unique')
    # ### end Alembic commands ###
